In [2]:
from selenium import webdriver

driver = webdriver.Chrome()

driver.get("https://app.smartwealthpro.com/MutualFund/StockHoldingChanges/Global-IME-Sammunat-Yojana-2/GBIMESY2?c=1092")

input("Interact with website then press Enter...")

apis = set()

for request in driver.requests:

    if request.response:

        if "/api/" in request.url:
            apis.add(request.url)

print("\nFOUND APIs:\n")

for api in apis:
    print(api)

Interact with website then press Enter...

AttributeError: 'WebDriver' object has no attribute 'requests'

In [ ]:
# muskasturid@gmail.com
# Nep@l2053

In [9]:
from selenium import webdriver
import json

options = webdriver.ChromeOptions()
options.set_capability("goog:loggingPrefs", {"performance": "ALL"})
driver = webdriver.Chrome(options=options)
driver.get("https://app.smartwealthpro.com")
input("👉 Interact with website then press ENTER...")
logs = driver.get_log("performance")
apis = set()

for entry in logs:
    try:
        message = json.loads(entry["message"])["message"]
        if message.get("method") == "Network.requestWillBeSent":
            params = message.get("params", {})
            request = params.get("request", {})
            url = request.get("url")
            if url and "/api/" in url:
                apis.add(url)

    except Exception:
        pass

print("\n=== FOUND APIs ===\n")

for api in sorted(apis):
    print(api)

👉 Interact with website then press ENTER...

=== FOUND APIs ===

https://app.smartwealthpro.com/api/GetAutoCompleteCompanies
https://app.smartwealthpro.com/api/GetLiveCommentaryTicker
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441374700
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441385635
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441390980
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441374705
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441385640
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441390985
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441374708
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441385643
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441390988
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441374707
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441385642
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441390987
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441374706
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441385641
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441390986
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=12&sectorId=0&sortBy=shareValue&_=1779441390989
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441370874
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441372752
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441374703
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441385638
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441390983
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441370873
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441372751
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441374702
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441385637
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441390982
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441374701
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441385636
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441390981
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441374704
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441385639
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441390984

In [6]:
# pip install blinker==1.6.2

# Get all the apis

In [10]:
from selenium import webdriver
import json

options = webdriver.ChromeOptions()
options.set_capability("goog:loggingPrefs", {"performance": "ALL"})

driver = webdriver.Chrome(options=options)

driver.get("https://app.smartwealthpro.com")
input("👉 Interact with website then press ENTER...")
logs = driver.get_log("performance")

apis = set()

for entry in logs:
    try:
        message = json.loads(entry["message"])["message"]

        if message.get("method") == "Network.requestWillBeSent":

            params = message.get("params", {})
            request = params.get("request", {})

            url = request.get("url")

            if url and "/api/" in url:
                apis.add(url)

    except Exception:
        pass

print("\n=== FOUND APIs ===\n")

for api in sorted(apis):
    print(api)

👉 Interact with website then press ENTER...

=== FOUND APIs ===

https://app.smartwealthpro.com/api/GetAutoCompleteCompanies
https://app.smartwealthpro.com/api/GetLiveCommentaryTicker
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441649230
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441656948
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441662665
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441649235
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441656953
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441662670
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441649238
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441656956
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441662673
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441649237
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441656955
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441662672
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441649236
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441656954
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441662671
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=1&sectorId=0&sortBy=shareValue&_=1779441662686
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=10&sectorId=0&sortBy=shareValue&_=1779441662695
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=11&sectorId=0&sortBy=shareValue&_=1779441662696
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=12&sectorId=0&sortBy=shareValue&_=1779441662697
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=2&sectorId=0&sortBy=shareValue&_=1779441662687
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=3&sectorId=0&sortBy=shareValue&_=1779441662688
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=4&sectorId=0&sortBy=shareValue&_=1779441662689
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=5&sectorId=0&sortBy=shareValue&_=1779441662690
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=6&sectorId=0&sortBy=shareValue&_=1779441662691
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=7&sectorId=0&sortBy=shareValue&_=1779441662692
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=8&sectorId=0&sortBy=shareValue&_=1779441662693
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=35&monthBsId=9&sectorId=0&sortBy=shareValue&_=1779441662694
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=1&sectorId=0&sortBy=shareValue&_=1779441662685
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=10&sectorId=0&sortBy=shareValue&_=1779441662676
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=11&sectorId=0&sortBy=shareValue&_=1779441662675
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=2&sectorId=0&sortBy=shareValue&_=1779441662684
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=3&sectorId=0&sortBy=shareValue&_=1779441662683
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=4&sectorId=0&sortBy=shareValue&_=1779441662682
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=5&sectorId=0&sortBy=shareValue&_=1779441662681
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=6&sectorId=0&sortBy=shareValue&_=1779441662680
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=7&sectorId=0&sortBy=shareValue&_=1779441662679
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=8&sectorId=0&sortBy=shareValue&_=1779441662678
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=36&monthBsId=9&sectorId=0&sortBy=shareValue&_=1779441662677
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=37&monthBsId=12&sectorId=0&sortBy=shareValue&_=1779441662674
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441643505
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441646799
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441649233
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441656951
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441662668
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441643504
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441646798
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441649232
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441656950
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441662667
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441649231
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441656949
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441662666
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441649234
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441656952
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441662669

In [11]:
from selenium import webdriver
import json

options = webdriver.ChromeOptions()
options.set_capability("goog:loggingPrefs", {"performance": "ALL"})

driver = webdriver.Chrome(options=options)

driver.get("https://app.smartwealthpro.com")
input("👉 Interact with website then press ENTER...")
logs = driver.get_log("performance")

apis = set()

for entry in logs:
    try:
        message = json.loads(entry["message"])["message"]

        if message.get("method") == "Network.requestWillBeSent":

            params = message.get("params", {})
            request = params.get("request", {})

            url = request.get("url")

            if url and "/api/" in url:
                apis.add(url)

    except Exception:
        pass
print("\n=== FOUND APIs ===\n")

for api in sorted(apis):
    print(api)

👉 Interact with website then press ENTER...

=== FOUND APIs ===

https://app.smartwealthpro.com/api/GetAutoCompleteCompanies
https://app.smartwealthpro.com/api/GetLiveCommentaryTicker
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441966317
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441983880
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779441997960
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779442012126
https://app.smartwealthpro.com/api/GetMarketStatus?_=1779442036129
https://app.smartwealthpro.com/api/GetMutualFundAssetsAllocation?companyId=885&_=1779442012134
https://app.smartwealthpro.com/api/GetMutualFundFinancials?companyId=885&reportType=&timeline=Monthly&period=&nature=company&dataSampleCount=1&dataPrecision=1&_=1779442012132
https://app.smartwealthpro.com/api/GetMutualFundNavComparision?companyId=885&companies=&fundManagerId=0&sortAsc=true&sortBy=Stock%20Symbol&reportType=peer-comparison&_=1779442012135
https://app.smartwealthpro.com/api/GetMutualFundStockHoldings?companyId=885&itemsCount=10&_=1779442012133
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441966322
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441983885
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=closed-end&_=1779441997965
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=matured&_=1779441966327
https://app.smartwealthpro.com/api/GetMutualFundSummary?type=open-end&_=1779441966326
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441966325
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441983888
https://app.smartwealthpro.com/api/GetMutualFundsDividend?_=1779441997968
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441966324
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441983887
https://app.smartwealthpro.com/api/GetMutualFundsSectorHolding?fiscalYearId=0&monthBsId=0&_=1779441997967
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441966323
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441983886
https://app.smartwealthpro.com/api/GetMutualFundsTopStockHolding?fiscalYearId=0&monthBsId=0&sectorId=0&sortBy=shareValue&_=1779441997966
https://app.smartwealthpro.com/api/GetNotificationSettingsByUserMode?_=1779442036151
https://app.smartwealthpro.com/api/GetNotificationSettingsByUserMode?_=1779442036152
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441958928
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441963880
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441966320
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441983883
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779441997963
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779442012129
https://app.smartwealthpro.com/api/GetNotificationsForUser?_=1779442036132
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441958927
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441963879
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441966319
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441983882
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779441997962
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779442012128
https://app.smartwealthpro.com/api/GetPortfolioSectorAndCompany?pageNo=1&itemsPerPage=9999&pagePerDisplay=10&_=1779442036131
https://app.smartwealthpro.com/api/GetStockDataForChart?companyId=885&_=1779442012131
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=0&monthBsId=0&_=1779442036134
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=0&monthBsId=1&_=1779442036135
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=0&monthBsId=2&_=1779442036136
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=1&_=1779442036194
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=10&_=1779442036203
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=11&_=1779442036204
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=12&_=1779442036205
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=2&_=1779442036195
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=3&_=1779442036196
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=4&_=1779442036197
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=5&_=1779442036198
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=6&_=1779442036199
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=7&_=1779442036200
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=8&_=1779442036201
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=32&monthBsId=9&_=1779442036202
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=1&_=1779442036177
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=1&_=1779442036178
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=1&_=1779442036180
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=10&_=1779442036191
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=11&_=1779442036192
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=12&_=1779442036193
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=2&_=1779442036179
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=2&_=1779442036181
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=3&_=1779442036182
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=4&_=1779442036183
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=4&_=1779442036184
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=5&_=1779442036185
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=5&_=1779442036186
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=6&_=1779442036187
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=7&_=1779442036188
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=8&_=1779442036189
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=34&monthBsId=9&_=1779442036190
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=1&_=1779442036165
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=10&_=1779442036174
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=11&_=1779442036175
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=12&_=1779442036176
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=2&_=1779442036166
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=3&_=1779442036167
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=4&_=1779442036168
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=5&_=1779442036169
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=6&_=1779442036170
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=7&_=1779442036171
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=8&_=1779442036172
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=35&monthBsId=9&_=1779442036173
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=1&_=1779442036153
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=10&_=1779442036162
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=11&_=1779442036163
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=12&_=1779442036164
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=2&_=1779442036154
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=3&_=1779442036155
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=4&_=1779442036156
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=5&_=1779442036157
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=6&_=1779442036158
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=7&_=1779442036159
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=8&_=1779442036160
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=36&monthBsId=9&_=1779442036161
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=0&_=1779442036150
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=1&_=1779442036137
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=10&_=1779442036146
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=11&_=1779442036147
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=11&_=1779442036148
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=12&_=1779442036149
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=2&_=1779442036138
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=3&_=1779442036139
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=4&_=1779442036140
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=5&_=1779442036141
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=6&_=1779442036142
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=7&_=1779442036143
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=8&_=1779442036144
https://app.smartwealthpro.com/api/GetStockWiseMutualFundStockHoldings?companyId=885&fiscalYearId=37&monthBsId=9&_=1779442036145
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441966318
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441983881
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779441997961
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779442012127
https://app.smartwealthpro.com/api/GetUserRewardPoint?_=1779442036130
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441966321
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441983884
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779441997964
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779442012130
https://app.smartwealthpro.com/api/feedback/getallcategory?_=1779442036133

In [14]:
type(list(apis)[0])

str

In [20]:
all_datasets=[]
for item in apis:
    if 'StockHoldings' in item:
        all_datasets.append(fetch_api_datadset(item))

LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS
LOGIN PAGE STATUS: 200
TOKEN FOUND
LOGIN STATUS: 200
LOGIN SUCCESS
API STATUS: 200
JSON SUCCESS

## all_the datasets

In [19]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

def fetch_api_datadset(urls):
    login_url = "https://app.smartwealthpro.com/Account/Login"
    api_url = urls
    USERNAME = "muskasturid@gmail.com"
    PASSWORD = "Nep@l2053"
    session = requests.Session()
    headers = {
        "User-Agent": "Mozilla/5.0",
        "Referer": login_url
    }
    response = session.get(login_url, headers=headers)
    print("LOGIN PAGE STATUS:", response.status_code)
    soup = BeautifulSoup(response.text, "html.parser")
    token = soup.find(
        "input",
        {"name": "__RequestVerificationToken"}
    )["value"]
    
    print("TOKEN FOUND")
    payload = {
        "__RequestVerificationToken": token,
        "UserName": USERNAME,
        "Password": PASSWORD,
        "RememberMe": "false"
    }
    login_response = session.post(
        login_url,
        data=payload,
        headers=headers
    )
    print("LOGIN STATUS:", login_response.status_code)
    if "Log in" in login_response.text:
        print("LOGIN FAILED")
    else:
        print("LOGIN SUCCESS")
    
    # STEP 5: ACCESS API
    api_headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://app.smartwealthpro.com/"
    }
    api_response = session.get(
        api_url,
        headers=api_headers
    )
    print("API STATUS:", api_response.status_code)
    try:
    
        data = api_response.json()
        print("JSON SUCCESS")
        df = pd.DataFrame(data)
        return df
        # df.to_csv(f"C:\\Users\\HP\\Desktop\\data_extractions\\extraced_datasets\\data_fetch_of_all_comoany\\all_final_datasets\\company_\\{folder_name}\\{end_points}.csv", index=False)
    except:
        pass

## Find How Mnay datasets or api are availables

In [21]:
len(all_datasets)

71

In [22]:
all_datasets[0]

,stockHoldingId,fiscalYearBS,fiscalYearAD,monthName,stocks,sectors,details,companies
0,0,2079/2080,2022/2023,Jestha,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,"[{'companyId': 11, 'sectorName': 'Commercial B...","[{'companyId': 11, 'companySymbol': 'EBL', 'co..."
1,0,2079/2080,2022/2023,Baisakh,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None
2,0,2079/2080,2022/2023,Chaitra,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None
3,0,2079/2080,2022/2023,Falgun,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None
4,0,2079/2080,2022/2023,Magh,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None

In [23]:
all_datasets[1]

,stockHoldingId,fiscalYearBS,fiscalYearAD,monthName,stocks,sectors,details,companies
0,0,2082/2083,2025/2026,Chaitra,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 13, 'sectorName': 'Commercial B...","[{'companyId': 11, 'companySymbol': 'EBL', 'co..."
1,0,2082/2083,2025/2026,Falgun,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 13, 'sectorName': 'Commercial B...",None
2,0,2082/2083,2025/2026,Magh,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 13, 'sectorName': 'Commercial B...",None
3,0,2082/2083,2025/2026,Poush,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 13, 'sectorName': 'Commercial B...",None
4,0,2082/2083,2025/2026,Mangsir,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 13, 'sectorName': 'Commercial B...",None

In [24]:
all_datasets[2]

,stockHoldingId,fiscalYearBS,fiscalYearAD,monthName,stocks,sectors,details,companies
0,0,2081/2082,2024/2025,Baisakh,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 13, 'sectorName': 'Commercial B...","[{'companyId': 13, 'companySymbol': 'GBIME', '..."
1,0,2081/2082,2024/2025,Chaitra,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 922, 'sectorName': 'Commercial ...",None
2,0,2081/2082,2024/2025,Falgun,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 922, 'sectorName': 'Commercial ...",None
3,0,2081/2082,2024/2025,Magh,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 922, 'sectorName': 'Commercial ...",None
4,0,2081/2082,2024/2025,Poush,"{'gbime': 'Commercial Banks', 'scb': 'Commerci...",None,"[{'companyId': 611, 'sectorName': 'Hydro Power...",None

In [26]:
all_datasets[3]['stocks']

0    {'lsl': 'Commercial Banks', 'gbime': 'Commerci...
1    {'lsl': 'Commercial Banks', 'gbime': 'Commerci...
2    {'lsl': 'Commercial Banks', 'gbime': 'Commerci...
3    {'lsl': 'Commercial Banks', 'gbime': 'Commerci...
4    {'lsl': 'Commercial Banks', 'gbime': 'Commerci...
Name: stocks, dtype: object

In [28]:
final_dfs=pd.concat(all_datasets)
final_dfs

,stockHoldingId,fiscalYearBS,fiscalYearAD,monthName,stocks,sectors,details,companies,sectorName,companyName,...,assetPercent,oneMonthChange,twoMonthChange,threeMonthChange,growthPercent,companyId,isListed,navDate,yearBS,monthNo
0,0,2079/2080,2022/2023,Jestha,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,"[{'companyId': 11, 'sectorName': 'Commercial B...","[{'companyId': 11, 'companySymbol': 'EBL', 'co...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2079/2080,2022/2023,Baisakh,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,2079/2080,2022/2023,Chaitra,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,2079/2080,2022/2023,Falgun,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,2079/2080,2022/2023,Magh,"{'ebl': 'Commercial Banks', 'sbi': 'Commercial...",None,[],None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0,2081/2082,2024/2025,Shrawan,"{'lsl': 'Commercial Banks', 'gbime': 'Commerci...",None,"[{'companyId': 922, 'sectorName': 'Commercial ...","[{'companyId': 11, 'companySymbol': 'EBL', 'co...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2080/2081,2023/2024,Asadh,"{'lsl': 'Commercial Banks', 'gbime': 'Commerci...",None,"[{'companyId': 922, 'sectorName': 'Commercial ...",None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,2080/2081,2023/2024,Jestha,"{'lsl': 'Commercial Banks', 'gbime': 'Commerci...",None,"[{'companyId': 11, 'sectorName': 'Commercial B...",None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,2080/2081,2023/2024,Baisakh,"{'lsl': 'Commercial Banks', 'gbime': 'Commerci...",None,"[{'companyId': 11, 'sectorName': 'Commercial B...",None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,2080/2081,2023/2024,Chaitra,"{'lsl': 'Commercial Banks', 'gbime': 'Commerci...",None,"[{'companyId': 11, 'sectorName': 'Commercial B...",None,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
final_dfs.to_csv(r"final_stocks_all_fiscals_years.csv",index=False)

In [30]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\data_extractions\\extraced_datasets\\data_fetch_of_all_comoany'