# Extract Kantipur

In [40]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time


options = Options()
driver = webdriver.Chrome(options=options)
driver.get("https://ekantipur.com/business")
time.sleep(3)

all_urls = []
for i in range(1, 5):
    try:
        path = f"/html/body/div[1]/div/div[{i}]/div/div[1]/h2/a"
        url = driver.find_element(By.XPATH, path).get_attribute("href")
        all_urls.append(url)
    
    except Exception as e:
        print(e)
        
news_data = []
for idx, url in enumerate(all_urls):
    try:
        driver.get(url)
        time.sleep(5)
        try:
            driver.find_element(By.XPATH,"/html/body/div[6]/div/div/div[2]/div/button").click()
            print("clicked")
        except Exception as e:
            print(e)
        time.sleep(2)
        title = driver.title
        news = driver.find_element(By.CLASS_NAME,"news-section-wrap-story").text
        news_data.append({"title": title,"news": news})

    except Exception as e:
        print(e)
driver.quit()
kantipur=pd.DataFrame(news_data)

clicked
clicked
Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[6]/div/div/div[2]/div/button"}
  (Session info: chrome=148.0.7778.217); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff7ce067de5+14895]
	chromedriver!GetHandleVerifier [0x7ff7ce067e50+14900]
	chromedriver!(No symbol) [0x7ff7cddcd5ad]
	chromedriver!(No symbol) [0x7ff7cde27822]
	chromedriver!(No symbol) [0x7ff7cde27b2c]
	chromedriver!(No symbol) [0x7ff7cde77d17]
	chromedriver!(No symbol) [0x7ff7cde7486f]
	chromedriver!(No symbol) [0x7ff7cde19df8]
	chromedriver!(No symbol) [0x7ff7cde1ace3]
	chromedriver!GetHandleVerifier [0x7ff7ce37cc49+3296f9]
	chromedriver!GetHandleVerifier [0x7ff7ce377375+323e25]
	chromedriver!GetHandleVerifier [0x7ff7ce39bc82+348732]
	chromedriver!GetHandleVerifier [0x7ff7ce086045+32af5]
	chromedriver!GetHandleVerifier [0x7ff7ce08ecec+3b79c]
	chromedriver!GetHandleVerifier [0x7ff7ce071bc4+1e674]
	chromedriver!GetHandleVerifier [0x7ff7ce071d54+1e804]
	chromedriver!GetHandleVerifier [0x7ff7ce0560e7+2b97]
	KERNEL32!BaseThreadInitThunk [0x7ffa84c9e957+17]
	ntdll!RtlUserThreadStart [0x7ffa85707c1c+2c]

In [41]:
df

,title,news
0,सुनको मूल्य तोलाको २ हजारले बढ्यो - कान्तिपुर,काठमाडौँ — नेपाली बजारमा आज सुन-चाँदीकै मूल्य ...
1,फैलिँदै बर्डफ्लु : १० जिल्लामा ५ लाख १५ हजार प...,काठमाडौँ — सरकारले बर्डफ्लु प्रभावित क्षेत्रमा...
2,करका दर हेरफेर र बजेटपूर्व सूचना चुहाएको भन्दै...,

In [14]:
import pandas as pd

In [15]:
pd.DataFrame(news_data)

,title,news
0,सुनको मूल्य तोलाको २ हजारले बढ्यो - कान्तिपुर,काठमाडौँ — नेपाली बजारमा आज सुन-चाँदीकै मूल्य ...
1,फैलिँदै बर्डफ्लु : १० जिल्लामा ५ लाख १५ हजार प...,काठमाडौँ — सरकारले बर्डफ्लु प्रभावित क्षेत्रमा...

## Online khabar

In [ ]:
# https://www.onlinekhabar.com/

In [ ]:
# /html/body/div[8]/div[2]/section[11]/div/h2/a
# /html/body/div[8]/div[2]/section[12]/div/h2/a


# skip this button 
# /html/body/div[1]/div/div/div/div[2]/span



# ok18-single-post-content-wrap
# ok18-single-post-content-wrap

# ok news

In [36]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
options.add_argument("--headless=new")
options.add_argument("--start-maximized")
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(options=options)
driver.get("https://www.onlinekhabar.com/")
time.sleep(10)

all_urls = []

for i in range(4, 7):
    try:
        path = f"/html/body/div[8]/div[2]/section[{i}]/div/h2/a"
        url = driver.find_element(By.XPATH, path).get_attribute("href")
        all_urls.append(url)
        print(url)

    except Exception as e:
        print(e)

news_data = []

for idx, url in enumerate(all_urls):
    try:
        driver.get(url)
        time.sleep(5)
        # close popup if exists
        try:
            driver.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div[2]/span").click()
        except:
            pass
        time.sleep(2)
        title = driver.title
        news = driver.find_element(By.CLASS_NAME, "ok18-single-post-content-wrap").text
        news_data.append({"title": title,"news": news})
    except Exception as e:
        print(e)
driver.quit()
ok=pd.DataFrame(news_data)
ok['news']=ok['news'].str.replace("News Summary\nGenerated by OK AI. Editorially reviewed.\n","")
ok

https://www.onlinekhabar.com/2026/06/1950222/foreign-currency-can-be-sent-5-percent-more-than-the-specified-amount-for-studying-abroad
https://www.onlinekhabar.com/2026/06/1950203/traffic-on-bp-highway-suspended-due-to-increased-floodwaters
https://www.onlinekhabar.com/2026/06/1950163/mahavir-pun-will-take-charge-of-the-former-sports-ministry

,title,news
0,विदेश अध्ययनका लागि तोकिएभन्दा ५ प्रतिशत धेरै ...,नेपाल राष्ट्र बैंकले विदेशमा अध्ययन गर्न जाने ...
1,रोशीको बहाव बढेपछि बीपी राजमार्गमा सवारी सञ्चा...,काभ्रेको रोशी खोलामा पानीको बहाव उच्च भएपछि सम...
2,साविकको खेलकुद मन्त्रालयमा हुनेछ महावीर पुनको ...,"नवनियुक्त विज्ञान, प्रविधि तथा नवप्रवर्तन मन्त..."

In [33]:
ok=pd.DataFrame(news_data)
ok['news']=ok['news'].str.replace("News Summary\nGenerated by OK AI. Editorially reviewed.\n","")
ok

,title,news
0,विदेश अध्ययनका लागि तोकिएभन्दा ५ प्रतिशत धेरै ...,नेपाल राष्ट्र बैंकले विदेशमा अध्ययन गर्न जाने ...
1,रोशीको बहाव बढेपछि बीपी राजमार्गमा सवारी सञ्चा...,काभ्रेको रोशी खोलामा पानीको बहाव उच्च भएपछि सम...
2,साविकको खेलकुद मन्त्रालयमा हुनेछ महावीर पुनको ...,"नवनियुक्त विज्ञान, प्रविधि तथा नवप्रवर्तन मन्त..."

In [39]:
ok['news'][2]

'नवनियुक्त विज्ञान, प्रविधि तथा नवप्रवर्तन मन्त्री महावीर पुनले साविकको खेलकुद मन्त्रालयको भवनमा पदभार ग्रहण गर्ने भएका छन् ।\nनयाँ मन्त्रालय भएकाले हालसम्म निश्चित भवन तयार नभएकाले खेलकुद मन्त्रालयको भवन रोजिएको हो ।\nमन्त्रालयकी सहसचिव मोनिका झाका अनुसार सचिव प्रमिला बज्रचार्यको कार्यकक्ष पनि सोही भवनमा व्यवस्थापन गरिएको छ ।\n२६ जेठ, काठमाडौं । विज्ञान, प्रविधि तथा नवप्रवर्तन मन्त्रीको रूपमा सांसद महावीर पुनले पदभार ग्रहण गर्दैछन् ।\nनयाँ मन्त्रालय गठन भएकोले अहिलेसम्म यसको व्यवस्थापन भइसकेको छैन । यसअघि शिक्षा मन्त्रालय भित्रकै विज्ञान प्रविधि शाखाभित्र रहेर कामकाज चलिरहेको छ । त्यसैले मन्त्रालयको कुनै निश्चित भवन तयारी भइनसकेकाले उनले कता पदभार ग्रहण गर्छन् भन्ने आमचासो देखिन्छ ।\nविज्ञान, प्रविधि तथा नवप्रवर्तन मन्त्रालयकी सहसचिव मोनिका झाका अनुसार पुनले साविकको खेलकुद मन्त्रालयको भवनमा पदभार ग्रहण गर्नेछन् ।\nमन्त्रालयको कामकाज हालसम्म शिक्षा अन्तर्गत रहेको साविककै महाशाखाबाट चलिरहे पनि मन्त्रीलाई भने साविकको खेलकुद मन्त्रालयमा राखिनेछ ।\nकेही समयअघि सरुवा भएर यस मन्त्रालयमा आएकी सचिव प्रमिला बज्रचार्यको कार्यकक्ष पनि साविककै खेलकुदमा व्यवस्थापन गरिएको थियो ।\n‘हामी अहिलेसम्म उता पूरै तयारी नसकिएकाले शिक्षाकै भवनभित्रबाट साविककै महाशाखाबाट काम गरिरहेका छौँ । क्रमशः उता संरचना बन्दै जाँदा हामी पनि सर्नेछौँ,’ झाले भनिन्, ‘तर, नयाँ आउनुभएको सचिवज्यूलाई पनि उतै कार्यकक्ष व्यवस्थापन गरियो । मन्त्रीज्यूको पनि उतै हुन्छ । अन्य संरचना निर्माण र व्यवस्थापनको काम भने जारी छ ।’'

In [35]:
# /html/body/div[8]/div[2]/section[10]/div/h2/a
# /html/body/div[8]/div[2]/section[4]/div/h2/a

## Bajar ko chirfar

In [45]:
options = Options()
options.add_argument("--headless=new")
options.add_argument("--start-maximized")
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

driver = webdriver.Chrome(options=options)

driver.get("https://bajarkochirfar.com/latest/")
time.sleep(5)
urls = []

for i in range(1,5):
    try:
        path=f"/html/body/div[1]/section/div/div[2]/div[{i}]/article/a[1]"
        url=driver.find_element(By.XPATH,path).get_attribute("href")
        urls.append(url)
    except:
        pass

news_data=[]
for url in urls:
    try:
        driver.get(url)
        time.sleep(2)
        news =(driver.find_element(By.XPATH,
                "/html/body/div[1]/div[1]/div/div[1]/main/div/div[1]/article/div").text)
        news_data.append({"title":driver.title,"news":news})
    except:
        pass

bajar_ko_chirfaar=pd.DataFrame(news_data)

In [47]:
pd.DataFrame(news_data)

,title,news
0,चार पटक मन्त्रिपरिषद् बैठक बस्दा पनि भएन बोर्ड...,नेपाल धितोपत्र बोर्ड (सेबोन) को अध्यक्ष नियुक्...
1,"एक कम्पनीको आईपीओ डिम्याट खातामा जम्मा हुँदै, ...",टक्सार पिखुवा खोला हाइड्रोपावर लिमिटेडले निष्क...
2,सुधन गुरुङ आज फेरि गृहमन्त्री बन्दै | BAJARKO ...,रास्वपा सांसद सुधन गुरुङ फेरि गृहमन्त्री बन्ने...
3,समस्याग्रस्त कर्णाली डेभलपमेन्ट बैंकले बचतकर्त...,कर्णाली डेभलपमेन्ट बैंक लिमिटेडले हालसम्म बचतक...

## nmepali paisa

In [61]:
import time
from selenium.webdriver.common.by import By


options = Options()
options.add_argument("--headless=new")
options.add_argument("--start-maximized")
options.add_argument("--window-size=1920,1080")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")


driver = webdriver.Chrome(options=options)
driver.get("https://nepalipaisa.com/news")
time.sleep(5)

urls = []
news_list = []

for i in range(1, 6):
    try:
        url = (driver.find_element(
            By.XPATH,
            f"//div//div[2]//div//div//div//div[1]//div//div[2]//div[{i}]//div//a"
        ).get_attribute("href"))
        urls.append(url)
        print(url)
    except Exception as e :
        print(e)

for url in urls:
    try:
        driver.get(url)
        time.sleep(2)

        news = driver.find_element(By.ID, "newsBody").text
        news_list.append({"title":driver.title,"news":news})
        
    except:
        continue

driver.quit()

nepali_paisa=pd.DataFrame(news_list)

https://nepalipaisa.com/news-detail/91657
https://nepalipaisa.com/news-detail/91656
https://nepalipaisa.com/news-detail/91655
None
https://nepalipaisa.com/news-detail/91653

In [ ]:
# /html/body/section[1]/div/div/div[2]/div/div[2]/div/div/div/div[1]/div/div[2]/div[4]/div/a
# /html/body/section[1]/div/div/div[2]/div/div[2]/div/div/div/div[1]/div/div[2]/div[3]/div/a

In [63]:
pd.DataFrame(news_list)

,title,news
0,Nepali Paisa | 'जेडब्ल्यू म्यारियट होटल काठमाड...,काठमाडौं: एमएस ग्रुप अन्तर्गतको कम्पनी क्यापिट...
1,"Nepali Paisa | बजेटमा समेटिए १० सुरुङमार्ग, रक...",काठमाडौं: सरकारले आगामी आर्थिक वर्ष २०८३-८४ मा...
2,Nepali Paisa | सुधन गुरुङसँगै महावीर पुनले पनि...,काठमाडौं: प्रधानमन्त्री बालेन्द्र शाहले विज्ञा...
3,Nepali Paisa | मन्त्रिपरिषद् बैठकले गर्‍यो चार...,काठमाडौं: आज मंगलबार बसेको मन्त्रिपरिषद् बैठकल...

In [62]:
news_list

[{'title': "Nepali Paisa | 'जेडब्ल्यू म्यारियट होटल काठमाडौं भ्याली' २०३१ सम्ममा सञ्चालनमा आउने",
  'news': 'काठमाडौं: एमएस ग्रुप अन्तर्गतको कम्पनी क्यापिटल होटल एन्ड हस्पिटालिटी लिमिटेड र विश्वप्रसिद्ध होटल चेन म्यारियट इन्टरनेसनलबीच नेपालमा पहिलो पटक ‘जेडब्ल्यू म्यारियट होटल काठमाडौं भ्याली’ सञ्चालन गर्न सम्झौता भएको छ।\n\nहोटललाई सन् २०३१ को प्रारम्भसम्ममा सञ्चालनमा ल्याउने लक्ष्य राखिएको छ। होटलमा २२१ वटा अत्याधुनिक र विलासी अतिथि कक्ष रहने जनाइएको छ।\n\nत्रिभुवन अन्तर्राष्ट्रिय विमानस्थलबाट करिब १५ मिनेटको दूरीमा रहने हुनाले पर्यटकका लागि यो निकै पायक पर्ने एमएस ग्रुपले जनाएको छ। यहाँबाट काठमाडौंका युनेस्को विश्व सम्पदा सूचीमा सूचीकृत स्थलहरूमा सहज पहुँच हुनेछ।\n\n\nहोटलमा विभिन्न स्वादका भोजनालय, स्पा, फिटनेस सेन्टर, स्विमिङ पुल र जेडब्ल्यू गार्डेन रहनेछन्। ठूला कर्पोरेट इभेन्ट र विवाहका लागि होटलमा १ हजार ६०० वर्ग मिटरभन्दा बढी क्षेत्रफलको विशाल कार्यक्रम तथा सभास्थल निर्माण गरिने जनाइएको छ।\n\nहोटल व्यवस्थापन सम्झौतापत्रमा क्यापिटल होटल एन्ड हस्पिटालिटी लिमिटेडका सञ्चालक तथा प्रबन्ध निर्देशक गौरव अग्रवाल र म्यारियट एशिया-प्यासिफिक (चीन बाहेक) का अध्यक्ष राज मेननले हस्ताक्षर गरेका छन्।\n\nसाथै क्यापिटल होटलका तर्फबाट शशीकान्त अग्रवाल र म्यारियट इन्टरनेसनलका तर्फबाट डेभिड म्यारियटबीच थप सम्झौता आदानप्रदान गरिएको थियो।'},
 {'title': 'Nepali Paisa | बजेटमा समेटिए १० सुरुङमार्ग, रकम विनियोजन भने लाखमा',
  'news': 'काठमाडौं: सरकारले आगामी आर्थिक वर्ष २०८३-८४ मा १० वटा सुरुङमार्गका लागि नाममात्रैको बजेट छुट्याएको छ। पूर्वाधार विकास मन्त्रालयले सुरुङमार्ग विकास कार्यक्रमका लागि एकदमै न्यून बजेट विनियोजन गरेको हो।\n\nपूर्वाधार विकास मन्त्रालयको रातो किताब अनुसार टोखा–छहरे गुर्जु भन्ज्याङ सुरुङमार्गका लागि ११ लाख ४८ हजार रुपैयाँ छुट्याइएको छ। यसैगरी सुर्खेतको भेरी नदीदेखि बर्दियाको दानुवा तालसम्म सुरुङमार्ग अध्ययन गर्न ५ लाख ६० हजार बजेट विनियोजन गरिएको छ।\n\nउता दोलालघाट चर्नावती सुरुङमार्गका लागि १८ लाख ९० हजार छुट्याइएको छ। हात्तीसार बबई सुरुङमार्गको लागि ७ लाख ५६ अर्ब रुपैयाँ विनियोजन गरिएको छ।\n\nसरकारले अन्य सुरुङमार्गका लागि शिर्षक राखे पनि बजेट राखेको छैन। विभिन्न प्रस्तावित सुरुङमार्गहरुको सम्भाव्यता अध्ययनका लागि १ लाख ९० हजार रुपैयाँ राखिएको छ। \n\nखुर्कोट चियावारी सुरुङमार्गका लागि ७ लाख ५६ हजार छुट्याइएको छ। शिवपुर भालुवाङ सुरुङमार्गका लागि ३ लाख ९२ हजार विनियोजन गरिएको छ। रानीघाट भुरीगाउँ सुरुङमार्गका लागि ३ लाख ९२ हजार नै बजेट छुट्याइएको छ। \n\nसिद्धबाबा सुरुङमार्ग निर्माणका लागि ५० करोड बजेट छुट्याइएको छ। यसैगरी ग्वार्को सातदोबाटो एकान्तकुना फ्लाइओभरका लागि १२ करोड ४६ लाख रुपैयाँ बजेट विनियोजन गरिएको छ। \n\nसरकारले नागढुंगा सुरुङमार्गका लागि भने १ अर्ब ९० करोड रुपैयाँ बजेट छुट्याएको छ।'},
 {'title': 'Nepali Paisa | सुधन गुरुङसँगै महावीर पुनले पनि मन्त्रीको शपथ लिँदै',
  'news': 'काठमाडौं: प्रधानमन्त्री बालेन्द्र शाहले विज्ञान, प्रविधि तथा नवप्रवर्तन मन्त्रीमा महावीर पुनलाई सिफारिस गरेका छन्। \n\nप्रधानमन्त्रीका प्रेस विज्ञ दीपा दाहालका अनुसार पुनको शपथ आज दिउँसो ३ बजे हुने भएको छ। पुन म्याग्दीबाट स्वतन्त्र सांसदका रूपमा निर्वाचित भएका हुन्। उनी सुशीला कार्की नेतृत्वको सरकारमा शिक्षामन्त्री थिए।  \n\nआज नै गृहमन्त्रीको रुपमा सुधन गुरुङले शपथ लिँदैछन्। सम्पत्तिको विषय विवादित भएपछि राजीनामा दिएका गुरुङमाथि छानबिन भएपछि पुन: नियुक्त हुन लागेका हुन्। '},
 {'title': 'Nepali Paisa | मन्त्रिपरिषद् बैठकले गर्\u200dयो चार निर्णय',
  'news': 'काठमाडौं: आज मंगलबार बसेको मन्त्रिपरिषद् बैठकले मुख्य चारवटा निर्णय गरेको छ। सरकारका प्रवक्ता सस्मित पोखरेलले आजका निर्णयहरू सार्वजनिक गरेका हुन्। \n\nयस्ता छन् मुख्य निर्णय\n१. तल्लो अरुण, लोअर न्यादी खोला, धुन्सा खोला र तादी खोल जलविद्युत् आयोजनालाई राष्ट्रिय वन क्षेत्र प्रयोग गर्न स्वीकृती दिने \n२. निजामती सेवा १६ औं संशोधन नियमावली २०८३ स्वीकृत गर्ने \n३. विशाल कुमार भण्डारी (दोलखा)को अध्यक्षतामा नेपाल रेडक्रस सोसाइटीको तदर्थ समिति गठन गर्ने \n४.पूर्वगृहमन्त्री एवम् प्रतिनिधि सभा सदस्य माननीय सुधन गुरुङका सम्बन्धमा अध्ययन तथा छानबिन गर्न गठित समितिले पेश गरेको प्रतिवेदन ग्रहण गर्ने '}]

In [64]:
# /html/body/div[1]/section/div/div[2]/div[5]/article/a[1]
# /html/body/div[1]/section/div/div[2]/div[4]/article/a[2]

In [65]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\New folder\\dat_news_multiple_sources'

In [ ]:
merged=pd.concat([nepali_paisa,bajar_ko_chirfaar,ok,kantipur],ignore_index=True)
merged[["news"]]